package io.github.barqdb.chat.server

/**
 * Room metadata is the only static content — just the topic list (icon/name/topic). The
 * numbers a room shows (people online, msg/s, messages stored) are all measured live, never
 * seeded here. Bot chatter and general text come from the vocab below.
 */

data class SeedRoom(
    val id: String, val icon: String, val name: String, val topic: String,
)

val SEED_ROOMS = listOf(
    SeedRoom("lobby", "🌐", "The Lobby", "say hi to the whole planet"),
    SeedRoom("gaming", "🎮", "Gaming HQ", "wow, halo, cod & more"),
    SeedRoom("music", "🎵", "Music Lounge", "now playing: everything"),
    SeedRoom("movies", "🎬", "Movies & TV", "no spoilers plz!!"),
    SeedRoom("tech", "💻", "Tech Talk", "gadgets, code & gizmos"),
    SeedRoom("sports", "⚽", "Sports Bar", "goooaaal ⚽"),
    SeedRoom("love", "💖", "Heart2Heart", "relationship advice ♥"),
    SeedRoom("random", "🎲", "Random", "totally random lol"),
)

val BOT_NAMES = listOf(
    "xX_ShadowNinja_Xx", "sk8er_grrl_92", "lolcatz2010", "D4rkKn1ght", "PixelPixie",
    "neon_dreamz", "iiMissBubblez", "RyderStorm_", "ghostwolf", "luna_star_x",
    "T3chW1zard", "blaze_it_up", "panda_luvr", "cyber_reb3l", "frostbyte", "MsSunshine07",
    "StarrySceneKid", "vampirewifi", "xxMallGothxx", "DJ_FloppyDisk", "tiny_dino_88",
    "glitterCrash", "dialup_diva", "ArcadeAce", "beepboop_bex", "SodaPopPunk",
    "moonlit_mochi", "ZomgItsKai", "retro_raven", "cassette_queen", "byte_me_plz",
    "CaptainCapsLock",
    "cosmicK8", "ModemMaven", "xoxCherryBomb", "VinylViolet", "TurboTasha",
    "ScreennameSam", "NiteLiteNora", "PixelPunk", "GlitchGuru", "MsnMaddie",
    "RingtoneRex", "BubbleByte", "ArcadeAngel", "ZeroCoolZara", "SceneBean",
    "KawaiiKoder", "RainyDayRay", "PunkRockPaige", "LinkinParked", "MangoModem",
    "BluRayBandit", "ForumFreak", "SparkleSyntax", "StaticSasha", "DotComDani",
    "ZipDriveZed", "TinyToolbar", "LaserLola", "WiredWillow", "AwayMsgAri",
    "NokiaNova", "FunkyFirewall", "CyberCami", "GlowstickGabe", "SleepyServer",
    "MyspaceMilo", "BitrateBella", "PixelParker", "CrushOnCrash", "RetroRina",
    "LolzLandon", "BriteByte", "DialToneDrew", "HotPinkHacker", "SnackPackSky",
    "XangaXena", "NeonNate", "CloudyCass", "MegaMika", "VHS_Vera",
)

val FLAGS = listOf(
    "🇺🇸", "🇧🇷", "🇯🇵",
    "🇬🇧", "🇩🇪", "🇮🇳",
    "🇰🇷", "🇨🇦", "🇫🇷",
    "🇦🇺", "🇲🇽", "🇳🇱",
    "🇲🇾", "🇸🇬", "🇵🇭",
    "🇹🇭", "🇮🇩", "🇻🇳",
    "🇪🇸", "🇮🇹", "🇵🇹",
    "🇸🇪", "🇿🇦", "🇳🇿",
    "🇦🇷", "🇨🇱", "🇨🇴",
    "🇵🇪", "🇺🇾", "🇨🇷",
    "🇵🇦", "🇯🇲", "🇮🇪",
    "🇳🇴", "🇩🇰", "🇫🇮",
    "🇵🇱", "🇨🇿", "🇬🇷",
    "🇹🇷", "🇺🇦", "🇷🇴",
    "🇭🇺", "🇨🇭", "🇦🇹",
    "🇧🇪", "🇪🇬", "🇳🇬",
    "🇰🇪", "🇲🇦", "🇬🇭",
    "🇸🇦", "🇦🇪", "🇶🇦",
    "🇮🇱", "🇵🇰", "🇧🇩",
    "🇱🇰", "🇳🇵", "🇨🇳",
    "🇭🇰", "🇹🇼", "🇧🇴",
    "🇵🇷", "🇩🇴", "🇨🇺",
)

/** Generic chatter used across every room. */
val BOT_TEXTS = listOf(
    "brb mom needs the fone lol", "asl?? :P", "anyone else here from myspace??",
    "rofl this room is poppin 😂", "add me on msn!! ✉", "omg hiii everyone (:",
    "how is this so fast?? theres literally 0 lag", "g2g dinner cya <3",
    "who wants to trade neopets", "blasting my fav song rn 🎧", "lol nice", "xD",
    "anyone got the new update yet", "my msg showed up INSTANTLY ⚡ wut",
    "greetings from brazil!! 🇧🇷", "hello from japan ✌",
    "typing from my sidekick lol", "wassup peeps 8)",
    "this is the fastest chat ive ever been in ngl", "no way this many ppl are online rn",
    "haha same", "omg yesss", "pics or it didnt happen :P",
    "brb refreshing... oh wait i dont even need to 😎", "anyone wanna be msn buddies",
    "cyaaa", "ttyl!!", "that was so fast i didnt even see it load",
    "im literally chatting with the whole planet rn 🌍",
    "how are we all in sync like this??", "lag who? never met her",
    "does anyone still use aim??", "my profile song is stuck in my head",
    "just changed my screen name again lol", "cyber cafe vibes rn",
    "i made a new avatar and its perfect", "wait this room is actually huge",
    "someone teach me how to make glitter text", "brb burning a mix cd",
    "my away message was too dramatic again", "hello from the future apparently",
    "this chat is faster than my brain", "anyone else up way too late",
    "new layout who dis", "i need more friends on here",
    "the refresh button is unemployed now", "ok this rules",
    "who just joined??", "my keyboard is louder than my speakers",
    "i miss when phones had buttons", "posting from the family computer",
    "my download has 3 hours left", "i should be doing homework rn",
    "anyone know good profile songs", "my top 8 is under review",
    "this room has main character energy", "i lost my password again",
    "caps lock is a lifestyle", "brb getting snacks",
    "someone make a forum sig for me", "my webcam is basically a potato",
    "do people still say w00t", "w00t w00t",
    "that loaded scary fast", "i blinked and 20 msgs appeared",
    "the chat scroll is going wild", "wait who pinged me",
    "im on a school computer lol", "dont tell the teacher",
    "my spacebar is fighting for its life", "this font is giving arcade",
    "new friend request accepted", "status update: still online",
    "brb changing my avatar again", "i need a cooler username",
    "everybody type your favorite color", "green chat bubbles would go hard",
    "somebody just signed in", "the sign in sound lives in my head",
    "i can hear the modem in my soul", "this is weirdly cozy",
    "shoutout to everyone lurking", "lurkers say hi",
    "ok who is making all these bots", "this place feels alive",
    "im saving this chat forever", "screenshotted for proof",
    "my battery is at 12 percent", "charger gang where u at",
    "dont kick me im cool", "mod check one two",
    "who remembers guestbooks", "leave a comment on my page",
    "i just learned html marquee", "sparkle cursor era was peak",
    "my playlist has 400 songs", "burned cd track 7 is cursed",
    "this chat has no chill", "typing race anyone",
    "i type faster when nervous", "my enter key is getting cooked",
    "just spilled soda on my desk", "the vibe is immaculate",
    "this is better than homework", "anyone got funny away messages",
    "brb gotta reboot", "reboot fixed nothing lol",
    "my username phase is showing", "i joined for five minutes and stayed",
    "why is everyone awake", "midnight chat hits different",
    "this would have broken my old laptop", "i need more stickers",
    "anyone else eating cereal rn", "i heard a notification in my dream",
    "do we have a theme song", "i nominate dial up noises",
    "this scroll speed is illegal", "somebody slow down the chat",
    "nah keep it fast", "im just here for chaos",
    "friendly reminder to hydrate", "ok back what did i miss",
    "i missed 200 messages??", "thread moved too fast",
    "the whole internet is in here", "waves from across the globe",
    "my browser is holding on", "no crash no problem",
    "who brought the good vibes", "new besties unlocked",
)

/** A little room-specific flavor on top of the generic chatter. */
val ROOM_TEXTS: Map<String, List<String>> = mapOf(
    "lobby" to listOf(
        "first time here be nice", "everyone say hi on 3", "this lobby is packed", "where is everybody from??",
        "new here what do i click", "lobby check in", "hello tiny internet people", "this is my first message",
        "anyone awake in here", "the lobby never sleeps", "i just found this place", "say your country flag",
        "roll call time", "this chat is packed today", "who has the coolest username", "everyone type lol at once",
        "public room energy", "new tab new friends", "welcome committee assemble", "ok this place is busy",
    ),
    "gaming" to listOf(
        "gg ez", "anyone on halo 2 rn?", "add me for co-op", "no scope!! 🎯",
        "lag switchers get out", "spawn campers smh", "one more match", "my clan tag is elite",
        "ranked queue is cursed", "my controller batteries died", "final boss time", "camping is not a strategy",
        "speedrun attempt 42", "loot drop pls", "party invite sent", "voice chat is chaos",
        "combo meter broken", "i need health packs", "respawn in 3", "achievement unlocked",
    ),
    "music" to listOf(
        "now playing: mcr 🎸", "aux cord is MINE", "this song is fire 🔥", "skip pls",
        "who made this playlist", "limewire finally finished", "send me that mp3", "band tees only",
        "shuffle is being dramatic", "this chorus is huge", "drums are too loud in a good way", "send playlist link",
        "ipod battery survived", "track 3 is underrated", "turn it up", "slow song break",
        "concert tickets when", "i know every lyric", "bass line is perfect", "repeat button stays on",
    ),
    "movies" to listOf(
        "NO SPOILERS", "just watched it omg", "team edward btw", "the twist tho 😱",
        "rewatching for the 5th time", "dvd menu music slaps", "pause i need popcorn", "that ending hurt",
        "director cut is better", "subtitles gang", "the trailer lied", "best scene incoming",
        "opening credits slap", "i need the soundtrack", "pause for snacks", "plot twist detected",
        "i cried at the ending", "that villain was iconic", "double feature tonight", "credits scene??",
    ),
    "tech" to listOf(
        "just flashed my sidekick", "html is a programming language fight me", "my dial up finally died", "got the new razr 📱",
        "defrag gang", "who broke the router", "rss feeds are underrated", "my laptop fan is screaming",
        "compiled first try somehow", "server is humming", "clear cache and pray", "who touched prod",
        "css is being rude", "ship it maybe", "localhost is my home", "terminal looks cool",
        "my cursor disappeared", "patch notes when", "new build just dropped", "keyboard shortcuts save lives",
    ),
    "sports" to listOf(
        "GOOOAL ⚽", "ref is blind smh", "did u see that play??", "we winning the cup this year",
        "offside!!", "overtime is stressful", "that save was unreal", "home team all day",
        "last minute winner", "crowd is loud today", "defense wake up", "what a comeback",
        "penalty drama", "my fantasy team is doomed", "bench went wild", "coach is stressed",
        "that replay was clean", "rivalry night lets go", "season starts now", "MVP chants",
    ),
    "love" to listOf(
        "he still hasnt texted back 😢", "we made it official 💕", "advice pls", "long distance is hard",
        "cutest couple here", "should i send the risky text", "my crush joined the room help", "matching profile pics when",
        "do i text first", "soft launch happened", "they liked my status", "cute but confusing",
        "send flowers or playlist", "we have matching songs", "date night soon", "heart status updated",
        "crush math is hard", "they remembered my birthday", "green flag moment", "group chat said yes",
    ),
    "random" to listOf(
        "why is cereal soup", "keyboard smash hours", "i have zero context and i agree", "who else is avoiding homework",
        "i forgot why i opened this tab", "someone explain the moon", "sandwich debate starts now", "my sock vanished",
        "orange juice after toothpaste is a crime", "what if keyboards had moods", "today feels like a loading screen", "i trust people with cool mugs",
        "tiny rant incoming", "my brain has 47 tabs", "who invented left turns", "i found a mystery cable",
        "floor snacks are forbidden", "nothing makes sense and thats fine", "random room doing random things", "i came here by accident",
    ),
)
